from pathlib import Path
from datetime import datetime
import re
import hashlib

ROOT = Path(__file__).resolve().parent.parent

PROMPTS_DIR = ROOT / "prompts"
MODULES_DIR = ROOT / "modules"
PROFILES_DIR = ROOT / "profiles"

COPILOT_INSTRUCTIONS = (
    ROOT / "copilot-instructions.md"
)

MODULE_PATTERN = re.compile(
    r"-\s+modules\/([a-zA-Z0-9\-_\.]+)"
)

SECTION_PATTERN = re.compile(
    r"<([a-zA-Z0-9\-_]+)>"
)

MAX_RUNTIME_PROMPT_SIZE_KB = 180


def read_file(path: Path) -> str:

    return path.read_text(
        encoding="utf-8"
    )


def validate_file_exists(path: Path):

    if not path.exists():

        raise FileNotFoundError(
            f"Missing required file:\n{path}"
        )


def extract_module_paths(profile_content: str):

    matches = MODULE_PATTERN.findall(
        profile_content
    )

    ordered_unique = []

    for match in matches:

        path = (
            MODULES_DIR / match
        )

        if path not in ordered_unique:
            ordered_unique.append(path)

    return ordered_unique


def validate_module_exists(module_paths):

    missing = [
        p for p in module_paths
        if not p.exists()
    ]

    if missing:

        raise FileNotFoundError(
            "Missing module files:\n" +
            "\n".join(str(m) for m in missing)
        )


def extract_sections(content: str):

    return SECTION_PATTERN.findall(
        content
    )


def detect_duplicate_sections(module_contents):

    seen = {}

    duplicates = []

    for module_name, content in module_contents:

        sections = extract_sections(
            content
        )

        for section in sections:

            if section in seen:

                duplicates.append(
                    (
                        section,
                        seen[section],
                        module_name
                    )
                )

            else:

                seen[section] = module_name

    return duplicates


def generate_checksum(content: str):

    return hashlib.sha256(
        content.encode("utf-8")
    ).hexdigest()[:12]


def validate_runtime_prompt_size(content: str):

    size_kb = round(
        len(content.encode("utf-8")) / 1024,
        2
    )

    if size_kb > MAX_RUNTIME_PROMPT_SIZE_KB:

        print(
            f"[WARN] Runtime prompt exceeds recommended size: {size_kb} KB"
        )

    return size_kb


def build_runtime_prompt(profile_path: Path):

    validate_file_exists(
        COPILOT_INSTRUCTIONS
    )

    profile_content = read_file(
        profile_path
    )

    module_paths = extract_module_paths(
        profile_content
    )

    validate_module_exists(
        module_paths
    )

    module_contents = []

    for module_path in module_paths:

        module_contents.append(
            (
                module_path.name,
                read_file(module_path)
            )
        )

    duplicates = detect_duplicate_sections(
        module_contents
    )

    if duplicates:

        print(
            "\n[WARNING] Duplicate XML sections detected:\n"
        )

        for section, first, second in duplicates:

            print(
                f"  Section <{section}> exists in both {first} and {second}"
            )

        print()

    assembled_sections = []

    assembled_sections.append(
        f"<!-- GENERATED RUNTIME PROMPT: {profile_path.name} -->"
    )

    assembled_sections.append(
        "<!-- DO NOT EDIT GENERATED FILE DIRECTLY -->"
    )

    assembled_sections.append(
        "<!-- GENERATED BY profile-builder.py -->"
    )

    assembled_sections.append(
        f"<!-- GENERATED AT: {datetime.utcnow().isoformat()}Z -->"
    )

    governance_content = read_file(
        COPILOT_INSTRUCTIONS
    )

    assembled_sections.append(
        governance_content
    )

    assembled_sections.append(
        profile_content
    )

    for _, module_content in module_contents:

        assembled_sections.append(
            module_content
        )

    final_content = "\n\n".join(
        assembled_sections
    )

    checksum = generate_checksum(
        final_content
    )

    final_content += (
        f"\n<!-- RUNTIME PROMPT CHECKSUM: {checksum} -->\n"
    )

    size_kb = validate_runtime_prompt_size(
        final_content
    )

    output_name = profile_path.name.replace(
        ".profile.md",
        ".prompt.md"
    )

    output_path = (
        PROMPTS_DIR / output_name
    )

    output_path.write_text(
        final_content,
        encoding="utf-8"
    )

    print(
        f"[OK] Generated runtime prompt: {output_path.name} ({size_kb} KB)"
    )


def build_all_profiles():

    profiles = sorted(
        PROFILES_DIR.glob(
            "*.profile.md"
        )
    )

    print(
        f"[INFO] Found {len(profiles)} profiles."
    )

    if not profiles:

        print(
            "[INFO] No profiles found."
        )

        return

    for profile in profiles:

        build_runtime_prompt(profile)

    print(
        "\n[INFO] Runtime prompt generation complete."
    )


if __name__ == "__main__":

    build_all_profiles()
